# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-15 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('caption', models.TextField(max_length=50)),
                ('likes', models.PositiveIntegerField()),
                ('comments', models.CharField(max_length=60)),
                ('profile_image', models.ImageField(blank=True, upload_to='profiles/')),
            ],
        ),
    ]
