# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-15 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stazone', '0003_image_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile_image',
        ),
    ]
